name: Build PR
on: pull_request_target
jobs:
  build:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts
      - name: Test
        env:
          BIBLIA_API_KEY: ${{ secrets.BIBLIA_API_KEY }}
          NODE_OPTIONS: --experimental-vm-modules
        run: yarn jest
